name: string_to_widgets
description: Get a list of widgets from a string by splitting the string at the notation blocks as per switch case statement and notations referencing the widgets.
version: 0.0.1
homepage: https://github.com/tarakparab/string_to_widgets

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
